# Generated by Django 5.2.5 on 2025-10-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_chatroom_is_active_chatroom_room_type_userprofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="friendrequest",
            name="unique_pending_request",
        ),
        migrations.AddField(
            model_name="message",
            name="anonymous_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("group", "Group"),
                    ("anonymous", "Anonymous"),
                ],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="app.chatroom",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="friendrequest",
            unique_together={("sender", "receiver")},
        ),
        migrations.AddField(
            model_name="friendship",
            name="user1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_initiated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("user1", "user2")},
        ),
    ]
