# Generated by Django 5.2.5 on 2025-10-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_friendship_remove_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
